-- ALTER TABLE  MODIFIY COLUMN : 제약사항 추가
CREATE TABLE MyTable28 (
	col1 INT,
    col2 INT,
    col3 INT,
    col4 INT
);

ALTER TABLE MyTable28
MODIFY COLUMN col1 INT UNIQUE;
ALTER TABLE MyTable28
MODIFY COLUMN col2 INT NOT NULL;
ALTER TABLE MyTable28
MODIFY COLUMN col3 INT DEFAULT 0;
ALTER TABLE MyTable28
MODIFY COLUMN col4 INT PRIMARY KEY DEFAULT 100;
DESC MyTable28;

-- ADD PRIMARY KEY : PRIMARY KEY 추가
CREATE TABLE MyTable29 (
	col1 INT,
    col2 INT,
    col3 INT
);
ALTER TABLE MyTable29
ADD PRIMARY KEY (col1, col2);
DESC MyTable29;